final Map<String, String> ar = {
  "cashee": "كاشي",
  "spending": "الإنفاق",
  "saving": "الإدخار",
  "top_up": "اضافة المال",
  "awesome": "رائع",
  "continue": "المتابعة",
  "continueAccountCreation": "الاستمرار في إنشاء الحساب",
  "setUpAccount": "إنشاء حساب",
  "signInOrSignUp": "سجّل الدخول أو قم بالاشتراك",
  "delete": "الحذف",
  "finish": "الإنتهاء",
  "allGood": "الأمور جيدة",
  "signOut?": "تسجيل الخروج؟",
  "signOut": "تسجيل الخروج",
  "forgotPasscode": "نسيت رمز المرور؟",
  "your_transactions_will_appear_here": "ستظهر عملياتك هنا",
  "sentACodeTo": "تم إرسال الرمز إلى @email",
  "no_email": "لم يصلك أي بريد إلكتروني؟ قم بطلبه مرة أخرى في غضون",
  "send_email": "ارسال بريد الكتروني جديد",
  "newCodeSent": "تم ارسال الرمز الجديد",
  "email": "البريد الإلكتروني",
  "chat": "المحادثة",
  "name": "الاسم",
  "cardReplace": "البطاقة البديلة",
  "cardPrintingInProgress": "جارى طباعة الكارت",
  "nameInEnglish": "الاسم بالانجليزية",
  "nameInArabic": "الاسم بالعربية",
  "twentyFourSeven": "24/7",
  "gender": "الجنس",
  "dateOfBirth": "تاريخ الميلاد",
  "birthCountry": "مكان الولادة",
  "nationality": "الجنسية",
  "idNumber": "رقم الهوية",
  "expiryDate": "تاريخ انتهاء الصلاحية",
  "phoneNumber": "رقم الهاتف",
  "deliveryAddress": "عنوان التوصيل",
  "contactSupport": "اتصل بخدمة دعم العملاء",
  "contactSupport.": "اتصل بخدمة دعم العملاء",
  "ContactSupport.": "اتصل بخدمة دعم العملاء",
  "needHelp": "تحتاج إلى المساعدة؟",
  "facingAnIssue": "هل تواجه مشكلة؟",
  "turnOnNotifications": "تشغيل الإشعارات",
  "refresh": "قم بتحديث الصفحة",
  "noCode": "ليس لديك رمز؟ اطلب رمزاً جديداً في غضون",
  "sendNewCode": "ارسال رمز جديد",
  "forgotPassword": "نسيت كلمة المرور",
  "enterYourEmail": "أدخل بريدك الإلكتروني",
  "useItToSignIn": "سوف تستخدمه لتسجيل الدخول إلى التطبيق",
  "enterCode": "أدخل الرمز",
  "enterMobileOtp": "أدخل رمز التأكد المرسل لك",
  "sentItTo": "لقد أرسلناه إلى @mobile",
  "createPassword": "قم بتكوين كلمة المرور",
  "createAppPasscode": "إنشاء رمز مرور خاص بالتطبيق",
  "codeHelpsYouAccess":
  "سيساعدك هذا الرمز في الدخول إلى التطبيق بسرعة في كل مرة. يرجى عدم مشاركة هذا الرمز مع أي أحد.",
  "weDontAskToEnterAgain": "يرجى التحقق من كلمة المرور الخاصة بك قبل المتابعة",
  "enterPasscodeAgain": "أدخل رمز المرور مرة أخرى",
  "everythingIsCorrect": "للتأكد من صحة جميع المعلومات",
  "something_went_wrong": "حدث شيء بالخطأ",
  "readAccept": "لقد قرأت وأوافق على الخاصة بكاشي",
  "privacyPolicy": "سياسة الخصوصية",
  "and": " & ",
  "termsAndConditions": "الشروط والخدمات",
  "showPass": "عرض كلمة المرور",
  "hidePass": "إخفاء كلمة المرور",
  "children": "أطفال",
  "activity": "نشاط",
  "activity_list_molecule.endOfList": "لقد وصلت إلى نهاية ! هذا كل شئ",
  "activity_list_molecule.noActivitiesAvailable": "لا توجد أنشطة متوافرة",
  "account": "الحساب",
  "completed": "تم إكماله",
  "expiry": "تاريخ الإنتهاء",
  "securityCode": "رمز الحماية",
  "cardNumberCopiedClipboard": "تم نسخ رقم البطاقة",
  "titleCopiedClipboard": "تم نسخ @title ",
  "unfreezeCard": "إلغاء تجميد البطاقة",
  "freezeCard": "تجميد البطاقة",
  "appleWallet": "محفظة آبل",
  "changePIN": "تغيير رمز المرور",
  "replaceCard": "استبدال البطاقة",
  "faq": "الأسئلة المتكررة",
  "createNewPasscode": "إنشاء رمز مرور جديد",
  "letsGo": "لننطلق !",
  "sendInvite": "أرسل دعوة",
  "slideToConfirm": "اسحب لتأكيد خيارك",
  "notifications": "الإشعارات",
  "application": "التطبيق",
  "transactions": "العمليات",
  "rateTheApp": "قييم التطبيق",
  "themes": "خلفيات الشاشة",
  "profile": "الملف الشخصي",
  "abdul": "Abdul",
  "azhar": "Azhar",
  "picture": "الصورة",
  "mom": "أمي",
  "dad": "ابي",
  "addChild": "أضف طفل",
  "DotFaq": "الأسئلة المتكررة",
  "termsServices": "شروط الخدمات",
  "version": "الإصدار @version",
  "password": "كلمة المرور",
  "passcode": "رمز المرور",
  "deleteAccount": "حذف الحساب",
  "passwordUpdated": "تم تحديث كلمة السر",
  "passcodeUpdated": "تم تحديث  رمز المرور",
  "enterNewPasscode": "أدخل رمز مرور جديد",
  "enterNewPassword": "أدخل كلمة مرور جديدة",
  "referral": "دعوة الاصدقاء",
  "challenges": "التحديات",
  "jobs": "الوظائف",
  "offers": "العروض",
  "rewards": "المكافآت",
  "charity": "التبرعات",
  "Hub": "مركز",
  "activateCard": "تفعيل البطاقة",
  "requestMoney": "اطلب المال",
  "yourTransactionsWillAppearHere": "ستظهر عملياتك هنا",
  "alright": "حسناً",
  "preparingYourNewCard": "بطاقتك الجديدة قيد التحضير",
  "verifyingYourDetails": "نحن نقوم بالتحقق من التفاصيل الخاصة بك",
  "bankRejectedRequest": "للأسف، لم يتم قبول طلبك",
  "bankRejectedYourRequest": "للأسف، لم يتم قبول طلبك",
  "cardIsCancelled": "البطاقة ملغية",
  "cardIsActive": "البطاقة فعالة",
  "cardIsFrozen": "البطاقة مجمدة",

  "usuallyTakesPendingSubtitle":
  "يستغرق الأمر عادةً يومي عمل. ثم سنرسل بطاقتك إلى شركة أرامكس التي ستتكفل بعملية التسليم.",
  "usuallyTakesNotIssuedSubtitle": "يستغرق من الوقت يومان عمل كحد أقصى. بعدها سنرسل لك البطاقة. ",
  "bankRejectedSubtitle":
  "سيقوم فريقنا للدعم الفني التواصل معك لحل المشكلة. إذا كنت تحتاج المساعدة، لا تتردد في استخدام الزر أدناه ",
  "deliveredSubtitle": "بما أنك استلمت بطاقتك، لنقم بتفعيلها",
  "cancelledSubtitle": "تم إلغاء بطاقتك",
  "activeSubtitle": "بطاقتك فعالة",
  "frozenSubtitle": "بطاقتك مجمدة",

  "activateTheCard": "الرجاء تفعيل بطاقتك",
  "request": "أطلب",
  "moneyRequested": "مبلغ المال المطلوب",
  "cancelRequest": "إلغاء الطلب",
  "goals_history": "تاريخ الأهداف",
  "createGoal": "أنشئ هدف",
  "oneYear": "سنة واحدة",
  "sixMonths": "ستة أشهر",
  "threeMonths": "ثلاثة أشهر",
  "oneMonth": "شهر واحد",
  "activate": "تفعيل",
  "cardWillArrive": "ستصلك البطاقة في غضون 7 أيام",
  "aramexWill": "ستتصل بك شركة أرامكس للحصول على عنوانك وتحديد موعد للتسليم",
  "costsSAR": " التكلفة هي SAR @replaceCardFee",
  "thisAmountWill": "سيتم خصم هذا المبلغ من رصيدك لتأكيد الاستبدال",
  "replaceCardTeen": "استبدل البطاقة",
  "replaceTheCard": "استبدال البطاقة؟",
  "youCannotUndo":
  "لتسديد مبلغ البطاقة البديلة سيتم خصم @replaceCardFee ريال سعودي من رصيد حساب anb. لا تسطيع إعادة هذه الخطوة",
  "confirmPay": "قم بتأكيد العملية ودفع @replaceCardFee SAR",
  "cardNumberAPIDisable": "رقم البطاقة API موقف",
  "allowanceSet": "تم تحديد المصروف الشخصي",
  "allowancePaused": "تم إيقاف المصروف الشخصي مؤقتاً",
  "allowanceUnavailable": "المصروف الشخصي غير متوفر",
  "cancelAllowance": "إلغاء المصروف الشخصي",
  "cancelAllowance?": "إلغاء المصروف الشخصي ؟",
  "yes": "نعم",
  "no": "لا",
  "frequency": "فترة التكرار",
  "setAllowance": "تحديد المصروف الشخصي",
  "nameAllowance": "المصروف الشخصي لـ@firstName ",
  "doNotShareItWith": "!الرجاء عدم مشاركة هذه المعلومات مع أي أحد",
  "pinChanged": "تم تغيير رمز المرور",
  "enterNewPin": "أدخل رمز المرور الجديد مرة أخرى",
  "toMakeSure": "للتأكد من صحة كل شيء",
  "thePinCodes": "رموز المرور (PIN) غير متطابقة. الرجاء المحاولة مرة أخرى.",
  "enterNewCardPin": "أدخل رمز مرور جديد للبطاقة",
  "thePinMayBeReq":
  "ربما سوف تحتاج رمز المرور (PIN)لعمليات الشراء داخل المتجر أو للتأكد من أنك صاحب البطاقة. لاتقم بمشاركة رمز الـ(PIN) مع أي أحد",
  "howMuchAndWhenDo": " ؟تريد الدفع ؟ كم ومتى",
  "weekly": "بشكل اسبوعي",
  "monthly": "بشكل شهري",
  "biweekly": "كل أسبوعين",
  "decline": "رفض",
  "slideToSend": "اسحب الشاشة للارسال",
  "moneySent": "تم إرسال المال",
  "weWillStillSendYou": "ستستمر في تلقي الإشعارات الهامة في وضع الاعدادات الاعتيادي",
  "turnOnNotification": "تشغيل الإشعارات لكاشي",
  "weSendOnlyEssential": "نرسل فقط التحديثات الأساسية لحسابك ونشاطك..",
  "familyTitle": "مسمى العائلة",
  "nickName": "اللقب المفضل",
  "nicknameUpdated": "تم تحديث اللقب المفضل",
  "updateNickname": "تحديث اللقب المفضل",
  "updateProfilePic": "تحديث صورة الملف الشخصي",
  "removeProfilePic": "تم حذف صورة الملف الشخصي بنجاح",
  "requestDeclined": "تم رفض الطلب",
  "declineNameRequest": "هل تريد رفض طلب @firstName ؟",
  "save": "حفظ",
  "picUpdate": "تم تحديث الصورة",
  "sentItToRegisteredMobileNumber": "لقد ارسلناه الى هاتفك الجوال المسجل لدينا",
  "passcodeDidntMatch": "رموز المرور غير متطابقة. حاول مرة أخرى",
  "toChangeYourEmail": "لتغيير بريدك الإلكتروني أو رقم هاتفك ",
  "test_select_user_screen.parent_app": "تطبيق الوالد",
  "test_select_user_screen.child_app": "تطبيق الطفل",
  "create_goal_controller.keep_your_skirt":
  "تمهل قليلًا. أعلي مبلغ يمكنك تحديده للهدف هو 1000 @currency",
  "create_goal_controller.goal_created": "تم إنشاء الهدف",
  "parent_children_wallet_section.savings_balance": "رصيد الادخار ، @currency",
  "parent_children_spend_tab.spending_balance": "",
  "parent_children_spend_tab.send_money": "ارسل المال",
  "parent_children_spend_tab.set_up_allowance": "تحديد المصروف الشخصي",
  "parent_children_spend_tab.regular_income_will":
  "الدخل المستمر يساعد ابنك في الادخار بشكل أفضل والانفاق بحكمة.",
  "goal_history_section.withdraw": "سحب المال",
  "goal_history_section.end_goal": "أنهي الهدف",
  "parent_children_screen.myANBBalance": "رصيدي في anb , @balance",
  "send_money_screen.toChild": "إلي @firstName",
  "send_money_screen.anbBalance": "رصيدي في anb , @balance",
  "send_money_screen.addMessage": "إضافة رسالة ؟",
  "send_money_screen.send": "أرسل",
  "send_money_screen.topUpYourAccount":
  "قم بإضافة المال لحسابك لإرسال المال إلي @firstName. رصيد حسابك: @balance",
  "send_money_success_screen.moneySentTo": "تم إرسال المال إلي @firstName",
  "send_money_controller.lowBalance": "لديك @balance فقط في رصيد حساب anb.",
  "app_screen.powered_by": "مدعم بواسطة",
  "create_anb_account_screen.createANBAccount": "انشئ حساب anb.",
  "create_anb_account_screen.toUseCashee":
  "لاستخدام كاشي تحتاج إلي حساب anb. نظرًا لعدم وجود حساب في هذا البنك سنساعدك في إنشاء حساب. تستغرق هذه العملية من دقيقتين إلي ثلاث دقائق",
  "create_anb_account_screen.haveAnIssue": "هل لديك مشكلة؟",
  "parent_verify_details_screen.verifyDetails": "نحن نقوم بالتحقق من التفاصيل الخاصة بك",
  "parent_verify_details_screen.processMayTakeTime":
  "سوف تستغرق هذه العملية من بضع ثوانٍ إلى بضع دقائق. قم  بتشغيل إشعارات التطبيق لنبلغك متى يمكنك المتابعة.",
  "parent_verify_details_controller.changeNationalId": "تغيير رقم الهوية الوطنية",
  "parent_account_ready_screen.accountReady": " حسابك جاهز",
  "parent_account_ready_screen.addYourChild":
  ".يجب عليك أن تنشئ ملفاً شخصياً لطفل واحد على الأقل. تسطيع إضافة المزيد فيما بعد عن طريق إعدادات الحساب",
  "parent_child_nid_screen.enterChildNid": "ادخل رقم الهوية الوطنية الخاص بطفلك",
  "parent_child_verify_details_screen.verifyDetails": "جاري التحقق من بيانات الطفل",
  "parent_child_verify_details_screen.processWillTakeTime":
  "سوف تستغرق هذه العملية من بضع ثوانٍ إلى بضع دقائق. قم  بتشغيل إشعارات التطبيق لنبلغك متى يمكنك المتابعة.",
  "parent_child_email_verification_screen.enterEmail": "أدخل البريد الإلكتروني لـ@name.",
  "parent_child_email_verification_screen.description":
  " سيستخدمه طفلك لتسجيل الدخول للتطبيق، وأيضا لاستلام رسائل بريد الكتروني هامة من كاشي والبنك العربي الوطني",
  "parent_child_confirm_email_screen.confirmEmail": "قم بتأكيد البريد الالكتروني",
  "parent_child_phone_screen.enterPhone": "ادخل رقم الهاتف الخاص بالطفل",
  "parent_child_phone_screen.alreadyCreated":
  "إذا قام طفلك بإنشاء ملفه الشخصي مسبقاً، فسوف نربطه بملفك عند إدخالك لنفس الرقم الذي استخدمه",
  "parent_child_all_set_screen.allSet": "!كل شيء جاهز",
  "parent_child_all_set_screen.sendMoney":
  "بطاقة @name بحاجة إلي التفعيل قبل أن تستطيع إرسال المال إليها. إلي أن يتم ذلك ، استمتع باستكشاف التطبيق",
  "incorrect_address_atom.incorrectAddress": "عنوان غير صحيح",
  "incorrect_address_atom.weUseTheAddress":
  "نحن نستخدم العنوان الذي قدمته لحسابك في anb . يمكنك تغييره في تطبيق anb  الخاص بك من إعدادات الحساب أو على ",
  "incorrect_address_atom.theANBWebsite": " موقع anb  الإلكتروني",
  "incorrect_address_atom.afterYouUpdate":
  "بعد تحديث العنوان، سيتم تحديثه تلقائيًا هنا. قد تستغرق هذه العملية بعض الوقت، لذا شغّل إشعاراتك وسنوافيك بآخر المستجدات. نحن نقوم بحفظ خطواتك، لذا يمكنك إغلاق تطبيق كاشي أثناء الانتظار.",
  "incorrect_address_atom.ifTheUpdateIsNot":
  "إذا لم يظهر التحديث في تطبيق كاشي، اضغط على زر 'تحديث'.",
  "incorrect_address_atom.ifYouStillFacing":
  "إذا كنت لا تزال تواجه مشكلة بعد تحديث العنوان الخاص بحسابك في anb، ",
  "incorrect_address_atom.contactOurSupport": "فاتصل بفريق الدعم لدينا",
  "parent_review_details_screen.reviewDetails": "قم بمراجعة التفاصيل",
  "parent_review_details_screen.weAreGoingToUse":
  "سيتم استخدام هذه التفاصيل لحساب كاشي الخاص بك. لتصحيح أي من التفاصيل، راجع خدمة دعم العملاء.",
  "parent_review_details_screen.aramexWillDeliver":
  "سيتم تسليم بطاقات كاشي إلى هذا العنوان، لذا يرجى التأكد من صحته. ",
  "parent_review_details_screen.incorrectAddress": "عنوان غير صحيح؟",
  "parent_child_review_details_screen.enterNameAndReview": "ادخل اسم طفلك وقم بمراجعة التفاصيل",
  "parent_child_review_details_screen.weAreGoingToUse":
  "سوف نستخدمها لحساب كاشي الخاص بهم. لتغيير أي من التفاصيل، ",
  "sign_in_password_screen.enterPassword": "ادخل كلمة المرور",
  "sign_in_password_screen.for": "للرقم @mobile",
  "email_verification_molecule.noAccount": "ليس لدي حساب",
  "choose_card_molecule.bolt_description_part1": "الطاقة، والتحفز، والعمل ",
  "choose_card_molecule.bolt_description_part2": "فرق بولت",
  "choose_card_molecule.bolt_description_part3":
  " .كل ماهو عن المغامرات والمرح واكتشاف الأشياء الجديدة",
  "choose_card_molecule.rocket_description_part1": "استكشاف آفاق جديدة وتحقيق أهداف كبيرة. مع ",
  "choose_card_molecule.rocket_description_part2": "فريق روكيت",
  "choose_card_molecule.rocket_description_part3": ".حدودنا هي السماء",
  "choose_card_molecule.heart_description_part1": "الشغف والحدس ونوع خاص من العناد. مع ",
  "choose_card_molecule.heart_description_part2": "فريق هارت",
  "choose_card_molecule.heart_description_part3": ".النجاح هو الاتزان مابين العقل والقلب",
  "parent_child_choose_card_screen.title": "اختر بطاقة",
  "parent_child_choose_card_screen.subTitle": "اسأل طفلك أي فريق يريد الانضمام اليه",
  "parent_set_profile_screen.setProfilePicture": "تحديد صورة الملف الشخصي",
  "parent_set_profile_screen.buildBetterConnection":
  "سيساعدنا ذلك في تحسين تجربة طفلك في التطبيق الخاص به",
  "set_profile_picture_organism.takePhoto": "التقط صورة",
  "set_profile_picture_organism.uploadFromGallery": "تحميل من الهاتف",
  "delete_picture_atom.deletePicture": "حذف الصورة",
  "setup_teen_set_profile_picture.setProfilePicture": "تحديد صورة الملف الشخصي",
  "setup_teen_set_profile_picture.thisIsHow": "هكذا سيراك والدك ومستخدمي كاشي الآخرين في التطبيق",
  "setup_teen_set_profile_picture.thisWillBeVisible":
  "سيكون هذا مرئيًا لوالدك والمستخدمين الآخرين. حدد صورتك الخاصة أو اختر واحدة من صورنا الرمزية!",
  "setup_teen_all_set_screen.readyToGo": "أنت الآن مستعد للبدء",
  "setup_teen_all_set_screen.exploreTheApp":
  "يمكنك طلب الأموال وإنفاقها فقط بعد تفعيل بطاقة كاشي  الخاصة بك. إلى أن يتم ذلك، استمتع باستكشاف التطبيق",
  "setup_teen_all_set_screen.createFlowSubtitle":
  "يمكنك طلب الأموال وإنفاقها فقط بعد تفعيل بطاقة كاشي  الخاصة بك. إلى أن يتم ذلك، استمتع باستكشاف التطبيق",
  "unlock_passcode_screen.title": "أدخل رمز المرور الخاص بك",
  "create_invite_parent_screen.ourWebsite": "موقعنا",
  "create_invite_parent_screen.appStore": "متجر آبل للتطبيقات",
  "create_invite_parent_screen.press": "اضغط",
  "create_invite_parent_screen.lucidity": "مقالات بأفكار واضحة",
  "create_invite_parent_screen.social": "مواقع التواصل الإجتماعي",
  "create_invite_parent_screen.insta": "انستجرام",
  "create_invite_parent_screen.fb": "فيس بوك",
  "create_invite_parent_screen.tiktok": "تيك توك",
  "create_invite_parent_screen.twit": "تويتر",
  "create_invite_parent_screen.linkedin": "لينكد ان",
  "parent_nickname_screen.howDoesYour": "بماذا يناديك طفلك؟",
  "parent_nickname_screen.makeAppFriendly": "سيساعدنا ذلك في تحسين تجربة طفلك في التطبيق الخاص به",
  "setup_teen_nickname_screen.whatIsYourNickname": "ما هو لقبك المفضل؟",
  "setup_teen_nickname_screen.useItForLeaderboards":
  "سنستخدمه بدلاً من اسمك الحقيقي لقائمه المتصدرين ، وغيرها من الميزات الاجتماعية التي نعمل على تطويرها",
  "setup_teen_nickname_screen.useItForReferalProgram":
  "سنستخدمه لبرنامج الاحالة الخاص بنا،و لقائمه المتصدرين ، وغيرها من الميزات الاجتماعية التي نعمل على تطويرها",
  "phone_number_screen.enterPhone": "أدخل رقم هاتفك",
  "choice_screen.greatWork": "عمل رائع حتى الآن! من فضلك عرّف عن نفسك",
  "choice_screen.parent": "أنا الوالد",
  "choice_screen.teen": "عمري يتراوح ما بين 6 و14 سنة",
  "parent_agreement_screen.createProfile": "لنقم بإنشاء الملف الشخصي للوالد",
  "parent_agreement_screen.ackImpStuff": "حدد المربعات أدناه لابلاغ طاقم العمل ",
  "parent_agreement_screen.father": "أنا أب أو وصي قانوني",
  "parent_profile_complete_screen.profileComplete": "!أصبح ملفك الشخصي مكتملاً",
  "parent_profile_complete_screen.nextStep":
  "الخطوة التالية - لنقم بإنشاء حسابك. سيتم حفظ خطواتك حتى تتمكن من المتابعة  من حيث توقفت  بسهولة.",
  "parent_child_account_connected_screen.connected": "تم ربط حساب طفلك بحسابك",
  "parent_nid_screen.enterYourNationalId": "أدخل رقم بطاقة الهوية الخاصة بك",
  "parent_nid_screen.requiredNid":
  "نحن نطلب بطاقة الهوية الخاصة بك ، بناءً على طلب البنك المركزي السعودي",
  "parent_child_nid_screen.enterYourNationalId": "أدخل رقم هوية طفلك",
  "setup_teen_agreement_screen.welcome": "اهلا بك قي الفريق @team !",
  "setup_teen_agreement_screen.setupAccount": "هيا لننشئ حسابك الخاص بكاشي ",
  "dob_molecule.notAParent":
  "يبدو أنك لست أحد الوالدين. يرجى الاتصال بخدمة دعم العملاء لتغيير نوع حسابك.",
  "dob_molecule.notATeen":
  "صممت كاشي خصيصاً لمن تتراوح أعمارهم ما بين 6 و 18 عامًا ولوالديهم. للأسف، إن عمرك ليس ضمن الحدود المقبولة. يرجى الاتصال بخدمة دعم العملاء للمزيد من التوضيح.",
  "dob_molecule.dobMolecule": "تعطلت الوظيفة الصارمة DOB تحليل جزيء",
  "parent_dob_screen.enterDob": "أدخل تاريخ ميلادك",
  "parent_child_dob_screen.enterDob": "أدخل تاريخ ميلاد طفلك",
  "email_verification_molecule.receiveEmails": "تلقي رسائل البريد الإلكتروني الأساسية حول نشاطك",
  "parent_confirm_email_controller.useAnotherEmail": "استخدم بريدًا إلكترونيًا آخر",
  "create_anb_account_screen.createAnbAccount":
  "بالفعل تم انشاء حساب ANB الخاصه بك وما زلت ترى هذه الرسالة ؟ اضغط على زر التنشيط",
  "parent_child_otp_controller.useAnotherPhone": "استخدم رقم هاتف آخر",
  "parent_activity_screen.allActivities": "كل الأنشطة",
  "parent_activity_screen.myTransactions": "معاملاتي",
  "parent_activity_screen.events": "الأحداث",
  "parent_activity_screen.noActivitiesAvailable": "لايوجد نشاطات متوفرة",
  "parent_activity_screen.endOfList": "!لقد قرأت كل شيء",
  "faq_screen.whatDoYouNeed": "بماذا تحتاج المساعدة؟",
  "faq_screen.didNotFindTheAns": "لم تجد الأجوبة التي تبحث عنها؟",
  "password_molecule.thePasswordMust": ":يجب أن تحتوي كلمة المرور على:",
  "password_molecule.number": "رقم",
  "password_molecule.tenCharacters": "أكثر من 10 أحرف",
  "password_molecule.upperLetter": "حرف كبير",
  "password_molecule.lowerLetter": "حرف صغير",
  "passcode_molecule.thePasscodeDidNotMatch": ". رمز المرور غير مطابق، حاول مرة أخرى",
  "apple_wallet_molecule.digits": "•••• 1820",
  "apple_wallet_molecule.cardAddedToApple": "تم إضافة البطاقة الى محفظة آبل",
  "apple_wallet_molecule.addYourCard": "أضف بطاقتك الى محفظة آبل",
  "apple_wallet_molecule.payInStores":
  "ادفع فى المتاجر أو اونلاين من خلال هاتفك المحمول في اي مكان متوفر به Apple Pay",
  "apple_wallet_molecule.addToAppleWallet": "أضف الى محفظة آبل",
  "apple_wallet_molecule.removeFromApple": "ازالة من محفظة آبل",
  "apple_wallet_molecule.removeTheCardFrom": "هل تريد إزالة البطاقة من محفظة آبل؟",
  "apple_wallet_molecule.youWontBeAble": "لن تستطيع الدفع ببطاقتك باستخدام الهاتف",
  "apple_wallet_molecule.remove": "إزالة",
  "apple_wallet_molecule.openAppleWallet": "فتح محفظة آبل",
  "text_field_atom.fieldIsMandatory": "مطلوب",
  "teen_card_atom.theCardIsFrozen": "البطاقة موقوفه",
  "teen_card_atom.spendingBalance": "رصيد الانفاق",
  "teen_card_atom.savingBalance": "رصيد الادخار",
  "teen_card_atom.sendMoney": "ارسل المال",
  "sign_out_atom.signOut": "تسجيل الجروج",
  "sign_out_atom.youWillHaveToEnter":
  "ستضطر لادخال رقم هاتفك والرقم السرى لتسجيل الدخول مرة اخرى",
  "request_money_parent_atom.hasRequested": "لقد طلب @name",
  "parent_request_money.asksFor": "لقد طلب @firstName",
  "request_button_atom.requested": "... تم الطلب ",
  "end_goal_atom.endWithdraw": "الانهاء والسحب",
  "create_goal_atom.createGoal": "اصنع هدفاً جديداً",
  "create_goal_atom.goalSubtitleParent": "تعلم ادخار المال هو مهارة حياتية مهمة. أنشئ هدفًا ل@firstName لتشجيعه / ها على البدء في الادخار لشيء ما.",
  "create_goal_atom.goalSubtitleTeen": "تعلم ادخار المال مثل اكتسابها. ابدأ بمبلغ صغير وحسن مهاراتك ",

  "cashee_card_atom.yourCardCancelled": "تم الغاء بطاقتك",
  "cashee_maintenance_screen.casheeMaintenanceScreen": "شاشة الصيانة لكاشي",
  "unlock_forgot_passcode_screen.resetPasscode": "هل تريد استعادة رمز المرور؟",
  "unlock_forgot_passcode_screen.willSendCodeTo":
  "سوف نرسل رمز لهاتفك المسجل لدينا. أدخل الرمز هنا لانشاء رمز مرور جديد",
  "unlock_forgot_passcode_screen.sendResetCode": "ارسل رمز الاستعادة",
  "create_teen_welcome_screen.welcomeTeamHeart": "اهلا بك في Team Heart!",
  "create_teen_welcome_screen.onlyYourNickname":
  "أنت بحاجة فقط لانشاء لقبك المفضل وصورة الملف الشخصي الآن!",
  "create_teen_invite_parent_screen.nowItsTimeToInvite": "حان الوقت الآن لدعوة والدك",
  "create_teen_invite_parent_screen.yourProfileHasBeen":
  "لقد تم إنشاء ملفك الشخصي. نحتاج الآن فقط من والدك أو وصيك القانوني اكمال عملية انشاء الحساب",
  "create_teen_invite_parent_screen.lovingCashee":
  "مستمتع بكاشي؟ شاركه مع اصدقائك وساعدهم في تنشئة شباب أذكياء في استخدام المال",
 "create_teen_invite_parent_screen.turnOnNotificationForApp":
"قم بتشغيل الاشعارات لنتمكن من ابلاغك متى تم انشاء حسابك. بعدها سوف تتمكن من إضافة اللمسات الأخيرة",
"create_teen_invite_parent_screen.turnOnNotification": "تشغيل الاشعارات",
"create_teen_invite_parent_screen.parentWantToLearn": "هل يريد الوالدين التعرف على كاشي؟",
"create_teen_invite_parent_screen.hereAreFewUseful":
"لديك بعض الروابط المفيدة التي تستطيع مشاركتها",
"create_teen_invite_parent_screen.linkCopied": "تم نسخ @title",
"create_teen_choose_card_screen.chooseYourCard": "اختر بطاقتك",
"create_teen_choose_card_screen.chooseWisely": "اختر بحذر - لا يمكنك تغييرها لاحقاً",
"create_teen_choose_card_screen.letCreateYourCashee";'?': "لننشئ ملفك الشخصي الخاص بكاشي",
"update_parent_nickname_screen.updateFamilyTitle": "تحديث مسمى العائلة",
"update_parent_profile_picture_screen.letYourChildBuild":
"سيساعد ذلك في تخصيص تجربة طفلك في التطبيق",
"parent_otpverify_screen.weSentItTo": "لقد ارسلناه الى @phone",
"spend_wallet_section.cardNumberAPIDisable": "رقم API البطاقه موقف",
"teen_setpin_alright_screen.doNotShareItWith": "!لا تقم بمشاركته مع أي أحد",
"teen_setpin_alright_screen.pinChanged": "تم تغيير رمز (PIN)",
"teen_setpin_confirm_screen.enterNewPin": "ادخل رمز (PIN) الجديد مره اخرى",
"teen_setpin_confirm_screen.toMakeSure": "للتأكد من أن كل شئ صحيح",
"teen_setpin_confirm_screen.thePinCodes":
"رمز المرور (PIN) غير صحيح. الرجاء المحاولة مرة أخرى.",
"teen_setpin_create_screen.enterNewCardPin": "ادخل رمز مرور (PIN) الجديد",
"teen_setpin_create_screen.thePinMayBeReq": "الرجاء عدم مشاركة رمز المرور (PIN) مع أي أحد",
"teen_replace_card_alright_screen.newCardOrdered": "تم طلب بطاقة جديدة",
"teen_replace_card_alright_screen.aramexWillContact": "ستتصل بك شركة أرامكس لاجراء عملية التسليم",
"teen_replace_card_screen.cardReplace": "البطاقة البديلة",
"teen_replace_card_screen.ifYouLostTheCurrent": "في حالة فقدان أو سرقة البطاقة",
"teen_replace_card_screen.yourCardWillBloc": "سيتم حظر بطاقتك!!",
"teen_replace_card_screen.youeAccountWill":
"سوف يكون حسابك في طور الاستعراض  فقط بشكل مؤقت. لن تستطيع استلام او انفاق المال حتى تفعل بطاقتك الجديدة",
"teen_replace_card_screen.cardWillArrive": "ستصل البطاقة الجديدة في خلال 7 أيام",
"teen_replace_card_screen.aramexWill":
"قد تتواصل معك شركة التوصيل الخاصة بنا أرامكس للحصول على عنوان ووقت التوصيل الخاص بك",
"teen_replace_card_screen.costsSAR": "التكلفة: 80 ريال سعودي",
"teen_replace_card_screen.thisAmountWill": "سيتم خصم المبلغ من حسابك",
"teen_replace_card_screen.replaceCard": "استبدل البطاقة",
"teen_replace_card_screen.replaceTheCard": "هل تريد استبدال البطاقة؟",
"teen_replace_card_screen.youCannotUndo":
"لا يمكنك إعاده هذه الخطوه، سوف يتم خصم مبلغ 60 ريال سعودي من رصيد anb لتسديد رسوم البطاقة البديلة",
"teen_replace_card_screen.confirmPay": "التأكيد ودفغ مبلغ 60 ريال",
"teen_replace_card_screen.orderANewCard": "طلب بطاقة جديدة",
"teen_replace_card_screen.iWouldLike":
"مرحباً، أود القيام بطلب إعادة اصدار بطاقة كاشي. أتفهم بأنه سوف يتم خصم مبلغ 60 ريال سعودي + 20% ضريبة قيمة مضافة كرسوم إعادة اصدار. أنا أؤكد بأن لدي المبلغ الكافي لأتمام هذه العملية. شكراً",
"request_money_screen.whatFor": "لماذا؟",
"request_money_success_screen.requestAmount": "المبلغ المطلوب يجب أن يكون أعلى من 0",
"goal_top_up_screen.spendingBal": "رصيد الانفاق :@currency",
"goal_top_up_screen.yourANBBalance": "رصيد anb الخاص بك :@currency",
"goal_history_screen.yourEnded": "ستظهر أهدافك المنجزة هنا",
"goal_history_screen.allTimeSaved": "currency@: كل ماتم ادخاره حتى الآن",
"create_goal_amount_screen.howMuchDo": "كم تريد أن تدخر؟",
"create_goal_amount_screen.createWithout": "انشئ دون مبلغ محدد للهدف",
"create_goal_deadline_screen.isThereDeadline": "هل هناك موعد آخر؟",
"create_goal_deadline_screen.createWithout": "انشئ دون إضافة آخر موعد",
"create_goal_deadline_screen.tapToSet": "من فضلك، اضغط للتحديد",
"create_goal_deadline_screen.specificDeadline": "آخر موعد محدد",
"create_goal_name_screen.whatAreYouSaving": "آخر موعد محدد؟",
"edit_goal_amount_screen.howMuchDo": "كم تريد أن  تدخر الآن؟",
"edit_goal_amount_screen.saveWithoutAmount": "أدخر دون مبلغ محدد للهدف",
"edit_goal_amount_screen.sheetTitle": "إن ازالة مبلغ الهدف يزيل آخر موعد أيضاً",
"edit_goal_amount_screen.sheetSubTitle":
"إذا أردت فقط الادخار دون هدف معين، قم بالاستمرار في الادخار وانهاء الهدف في أي تاريخ آخر ترغب فيه",
"edit_goal_amount_screen.sheetCtaBtn": "إزالة آخر موعد",
"edit_goal_deadline_screen.whenDeadline": "متى آخر موعد؟",
"edit_goal_deadline_screen.newDeadline": "آخر موعد جديد؟",
"edit_goal_deadline_screen.saveWithoutDeadline": "أدخر دون آخر موعد",
"goal_details_screen.unfreeze": "قم بإلغاء تجميد البطاقة لتعديل الهدف",
"goal_details_screen.activate": "قم بتفعيل بطاقتك الجديدة لتعديل الهدف",
"goal_history_section.unfreeze": "قم بإلغاء تجميد البطاقة لإضافة المال وإجراء السحب",
"goal_history_section.activate": "قم بتفعيل بطاقتك الجديدة لإضافة المال وإجراء السحب",
"goal_history_section.normalUnfreeze": "قم بإلغاء تجميد البطاقة لإضافة المال وإنهاء الأهداف",
"goal_history_section.normalActivate": "قم بتفعيل بطاقتك الجديدة لإضافة المال وإنهاء الأهداف",
"goal_topup_success_screen.addedTo": "تم اضافته ل @goalName'",
"goal_topup_screen.goalForName": "@goalName ل @firstName",
"goal_withdraw_success_screen.teenTitle": "تم سحبه لرصيد الإنفاق بنجاح",
"goal_withdraw_success_screen.parentTitle": "تم سحبه لرصيد @firstName للانفاق",
"goal_withdraw_screen.available": "balance@: المتوفر",
"goals_section.unfreeze": "قم بإلغاء تجميد البطاقة لإنشاء هدف جديد",
"goals_section.activate": "قم بتفعيل بطاقتك الجديدة لإنشاء هدف جديد",
"request_location_screen.no_permission_ui.title": "اسمح بتحديد موقعك أثناء استخدام التطبيق",
"request_location_screen.no_permission_ui.subtitle":
"إن تحديد موقعك ضروري لاستخدام كاشي وفقًا للوائح المملكة العربية السعودية. يساعدنا ذلك على إبقاء حسابك آمنًا. يرجى التأكد من اختيار \"السماح أثناء استخدام التطبيق\"",
"request_location_screen.no_permission_ui.button": "تشغيل خاصية تحديد الموقع",
"request_location_screen.limited_permission_ui.title":
"الرجاء اختيار 'السماح أثناء استخدام التطبيق' مع الموقع المحدد'",
"request_location_screen.limited_permission_ui.subtitle":
"إن تحديد موقعك ضروري لاستخدام كاشي وفقًا للوائح المملكة العربية السعودية حول الأمان والامتثال. الرجاء مساعدتنا في ذلك حتى تكون تجربتك أكثر أمانًا.",
"request_location_screen.limited_permission_ui.button": "إعدادات تحديد الموقع",
"location_service.enable_location_sharing.notifier1": "الرجاء تشغيل خدمات تحديد الموقع",
"location_service.enable_location_sharing.notifier2":
"الرجاء تحديد 'السماح أثناء استخدام التطبيق'",
"location_service.enable_location_sharing.notifier3": "الرجاء السماح بتحديد الموقع",
"location_service.enable_location_sharing.notifier4":
"اذهب الى اعدادات تطبيق كاشي واسمح باستمرار تحديد الموقع",
"parent_replace_card_screen.ifLostTheCurrent": "إذا فقد طفلك البطاقة الحالية أو تعرضت للسرقة",
"parent_replace_card_screen.cardWillbeBlock": "سيتم حظر بطاقه @firstName",
"parent_replace_card_screen.thisDoesNot":
"لن يؤثر ذلك على حسابك. سيتغير حساب طفلك الى عرض المشاهدة فقط. لن يتمكن طفلك من اجراء أي تحويل، ولن تستطيع أن ترسل له أي مبلغ من المال",
"parent_replace_card_screen.notEnoughFund": "لا يوجد رصيد كافي",
"parent_replace_card_screen.youNeedAtLeast":
"تحتاج على الاقل الي @replaceCardFee ريال سعودي فى حساب anb الخاص بك لدفع رسوم البطاقة البديلة. إذا أردت حظر جميع العمليات التي تخص البطاقة الى أن يتم اضافة المال، فيمكنك تجميد البطاقة من إعدادات البطاقة",
"children_card_view_controller.thereIsSomeProblem":
"يوجد مشكلة في تغيير حالة البطاقة. الرجاء المحاولة في وقت لاحق",
"teenHomeController.thereIsSomeProblem":
"يوجد مشكلة في تغيير حالة البطاقة. الرجاء المحاولة في وقت لاحق",
"dummy_card_activation_screen.cardActivateSuccess": "! تم تفعيل البطاقة بنجاح",
"dummy_card_activation_screen.activateYourCasheeCard": "قم بتفعيل بطاقة كاشي الخاصة بك",
"dummy_card_activation_screen.activateCashee": "قم بتفعيل بطاقة @firstName الخاصة بكاشي",
"dummy_card_activation_screen.enterTheLast4Digit":
"أدخل آخر 4 أرقام من بطاقة كاشي الخاصة بك لتفعيلها",
"dummy_card_activation_screen.enterTheLastDigit":
"ادخل آخر 4 ارقام من بطاقة كاشي ب @firstName لتفعيلها",
"parent_children_details_screen.unfreeze":
"قم بإلغاء تجميد بطاقة طفلك لتتمكن من ارسال المال له وليتمكن هو من استخدام البطاقة مره اخرى",
"parent_children_details_screen.yourCardIs": "لم يتم اصدار بطاقتك بعد",
"parent_children_details_screen.yourCard":
"تم إلغاء بطاقتك. الرجاء التواصل مع الدعم الفني لاصدار بطاقة جديدة.",
"parent_children_details_screen.activate":
"قم بتفعيل بطاقة طفلك لتتمكن من ارسال المال له وليتمكن هو من استخدام البطاقة ",
"parent_children_spend_tab.unfreeze": "قم بإلغاء تجميد البطاقة لارسال المصروف الشخصي",
"parent_children_spend_tab.unfreezeTheCard": "قم بإلغاء تجميد البطاقة لتحديد المصروف الشخصي",
"allowance_preview_screen.editAllowance": "تعديل المصروف الشخصي",
"allowance_preview_screen.amountWhen": "المبلغ ومتى تقوم بالدفع",
"allowance_date_screen.forMonthsWith":
"للأشهر التي يوجد بها أيام أقل، سوف يتم ارسال المال في آخر يوم في الشهر",
"allowance_frequency_screen.howOftenDoYou": "كم مرة تريد أن ترسل المال الى @firstName ؟",
"allowance_frequency_screen.TheEasiest": "الأفضل للمبتدئين لتعلم كيفية عمل الميزانية",
"allowance_frequency_screen.aSubstantial": "للذين لديهم القدرة على التخطيط المبكر",
"allowance_frequency_screen.letPlanLike": "للذين يستطيعون المحافظة على الميزانية",
"parent_topup_screen.anbBalanceEquals": "رصيد anb يساوي رصيد كاشي",
"parent_topup_screen.inCasheeYou":
"في كاشي أنت تستخدم المال من حساب anb الخاص بك. إذا كنت بحاجة الى المزيد من المال، اضف بكل بساطة مالاً الى حسابك في anb  باسخدام اسمك ورقم الـ IBAN ",
"request_money_pending_controller.cancelMoney": "إلغاء طلب المال؟",
"request_money_pending_controller.theRequestWillBe": "سيتم إلغاء الطلب لك ولوالدك",
"request_money_pending_controller.teenCancelled": "الغى/الغت الشاب/الشابة طلب المال",
"parent_nid_expiry_screen.enterExpiry": "ادخل تاريخ انتهاء الهوية الوطنية",
"nid_expiry_molecule.nidExpired": "لقد انتهت صلاحية هويتك الوطنية",
"request_money_pending_controller.requestCancelled": "تم إلغاء الطلب",
"walkthroughTitle1": "حلول مصرفية للشباب",
"walkthroughSubTitle1": "طريقة جديدة تماماً للتعلم، والكسب، والتوفير، والإنفاق للأطفال والشباب",
"walkthroughTitle2": "وظّف أموالك واستفد منها بأفضل طريقة",
"walkthroughSubTitle2": "تتبع الإنفاق بدقة وتعلم كيفية الإنفاق بحكمة",
"walkthroughTitle3": "حقق أهداف التوفير",
"walkthroughSubTitle3": "أصبح توفير الأموال أمرًا سهلاً عن طريق وضع الأهداف وطرق تتبع المال",
"walkthroughTitle4": "انطلق بثقة",
"walkthroughSubTitle4": "شركاؤنا هم الأفضل لتوفير تجربة آمنة ومضمونة",
"walkthroughTitle5": "تعلم كيفية كسب المكافآت",
"walkthroughSubTitle5":
"!دروس مبسطة عن الأموال مع إمكانية كسب المكافآت وعملات كاشي الافتراضية لجعل التعلم أمراً ممتعًا",
"reset_password_screen.resetPassword": "استعادة كلمة المرور؟",
"reset_password_screen.weWillSendCode": "سوف نرسل رمزًا لـ @phone",
"reset_password_screen.sendResetCode": "ارسل رمز الاستعادة",
"reset_new_password_screen.saveNewPassword": "حفظ كلمة المرور الجديدة",
"parentChildrenGoalSection.unfreezeCreateNewGoal": "قم بإلغاء تجميد بطاقة طفلك لانشاء هدف جديد",
"parentChildrenGoalSection.activateCreateNewGoal": "قم بتفعيل بطاقة طفلك لانشاء هدف جديد",
"spendWalletSection.activate": "سوف تتمكن من ارسال واستقبال المال عندما تقوم بإلغاء تجميد بطاقتك",
"spendWalletSection.frozen": "سوف تتمكن من ارسال واستقبال المال عندما تقوم بإلغاء تجميد بطاقتك",
"editGoalController.nameCover": "تم تحديث الاسم والشعار الرئيسي",
"editGoalController.amountDeadline": "تحديد مبلغ الهدف وآخر موعد له",
"goalDetailsController.endGoal": "إنهاء الهدف؟",
"goalDetailsController.body": "سوف يذهب من الهدف الى رصيد الانفاق @savedAmount",
"goalTopupController.insufficientErrorMsg": "رصيد إنفاقك هو: @spendBalance",
"goalWithdrawController.insufficientErrorMsg": "لديك فقط @saveBalance لإجراء السحب",
"teenProfileController.max20characters": "٢٠ حرف بحد أقصى",
"gallery": "معرض الصور",
"goal_history.emptyList": "كل التحويلات المالية لتحقيق الهدف ستظهر هنا.",
"parent_replace_card_screen.amountWillBe": "سيتم خصم هذا المبلغ من حسابك",
"parent_replace_card_screen.cardWillArrive": "ستصل بطاقتك الجديدة خلال 7 أيام",
"parent_replace_card_screen.costsSAR": "تكلفة الخدمة: @replaceCardFee SAR",
"parent_replace_card_screen.courierCompany": "شركة الشحن ستتواصل معك للحصول علي العنوان و رقم هاتفك للتواصل",
"parent_replace_card_waiting_screen.deliveredSubtitle": "لقد تلقيت بطاقتك الجديدة. الخطوة القادمة هي تفعيلها!",
"parent_request_money.hasRequested": "لقد طلب @firstName",
"parent_review_details_screen.cardsWillBeDelivered": "سيتم توصيل بطاقات كاشي لهذا العنوان لذلك الرجاء التأكد من أنه العنوان الصحيح.",
"send_money_controller.zeroBalance": "رصيد حسابك في anb هو: @balance. أضف مالًا لحسابك لإرسال المال.",
"sentItToNumber": "لقد أرسلناه إلي @number."
};