final Map<String, String> en = {
  "cashee": "Cashee",
  "spending": "Spending",
  "saving": "Saving",
  "top_up": "Top up",
  "awesome": "Awesome",
  "continue": "Continue",
  "continueAccountCreation": "Continue account creation",
  "setUpAccount": "Set up account",
  "signInOrSignUp": "Sign in or Sign up",
  "delete": "Delete",
  "finish": "Finish",
  "allGood": "All good",
  "signOut?": "Sign Out?",
  "signOut": "Sign out",
  "gallery": "Gallery",
  "facingAnIssue": "Facing an issue?",
  "forgotPasscode": "Forgot passcode?",
  "your_transactions_will_appear_here": "Your transactions will appear here",
  "sentACodeTo": "We've sent it to @email",
  "no_email": "No email? Request a new one in",
  "send_email": "Send a new email",
  "newCodeSent": "New code sent",
  "email": "Email",
  "chat": "Chat",
  "name": "Name",
  "cardReplace": "Card replacement",
  "nameInEnglish": "Name in English",
  "nameInArabic": "Name in Arabic",
  "twentyFourSeven": "24/7",
  "gender": "Gender",
  "dateOfBirth": "Date of birth",
  "birthCountry": "Birth Country",
  "nationality": "Nationality",
  "idNumber": "ID number",
  "expiryDate": "Expiry date",
  "phoneNumber": "Phone number",
  "deliveryAddress": "Delivery address",
  "contactSupport": "Contact support",
  "contactSupport.": "contact support",
  "ContactSupport.": "Contact support.",
  "needHelp": "Need help? ",
  "turnOnNotifications": "Turn on notifications",
  "refresh": "Refresh",
  "noCode": "No code? Request a new one in",
  "sendNewCode": "Send a new code",
  "forgotPassword": "Forgot password",
  "enterYourEmail": "Enter your email",
  "useItToSignIn": "You’ll use it to sign in to the app",
  "enterCode": "Enter the code",
  "enterMobileOtp": "Enter mobile OTP",
  "sentItTo": "We’ve sent it to @mobile",
  "createPassword": "Create password",
  "createAppPasscode": "Create app passcode",
  "codeHelpsYouAccess":
      "This code will help you access the app quickly each time. Please do not share this with anyone.",
  "weDontAskToEnterAgain": "Please check your password before proceeding",
  "enterPasscodeAgain": "Enter passcode again",
  "everythingIsCorrect": "To make sure everything is correct",
  "something_went_wrong": "Something went wrong!",
  "readAccept": "I have read & accept Cashee's ",
  "privacyPolicy": "Privacy Policy",
  "and": " & ",
  "termsAndConditions": "Terms and Conditions",
  "showPass": "Show password",
  "hidePass": "Hide password",
  "children": "Children",
  "activity": "Activity",
  "account": "Account",
  "completed": "Completed",
  "expiry": "Expiry",
  "securityCode": "Security code",
  "cardNumberCopiedClipboard": "Card number copied to clipboard.",
  "titleCopiedClipboard": "@title copied to clipboard",
  "unfreezeCard": "Unfreeze\ncard",
  "freezeCard": "Freeze\ncard",
  "appleWallet": "Apple\nWallet",
  "changePIN": "Change\nPIN",
  "replaceCard": "Replace\ncard",
  "faq": "FAQ",
  "createNewPasscode": "Create new passcode",
  "letsGo": "Let's go!",
  "sendInvite": "Send invite",
  "slideToConfirm": "Slide to confirm",
  "notifications": "Notifications",
  "application": "Application",
  "transactions": "Transactions",
  "rateTheApp": "Rate the app",
  "themes": "Themes",
  "profile": "Profile",
  "abdul": "Abdul",
  "azhar": "Azhar",
  "picture": "Picture",
  "mom": "Mom",
  "dad": "Dad",
  "addChild": "Add child",
  "DotFaq": "F.A.Q.",
  "termsServices": "Terms Services",
  "version": "Version @version",
  "password": "Password",
  "passcode": "Passcode",
  "deleteAccount": "Delete account",
  "passwordUpdated": "Password updated",
  "passcodeUpdated": "Passcode updated",
  "enterNewPasscode": "Enter new passcode",
  "enterNewPassword": "Enter new password",
  "referral": "Referral",
  "challenges": "Challenges",
  "jobs": "Jobs",
  "offers": "Offers",
  "rewards": "Rewards",
  "charity": "Charity",
  "Hub": "Hub",
  "activateCard": "Activate card",
  "requestMoney": "Request Money",
  "yourTransactionsWillAppearHere": "Your transactions will appear here",
  "alright": "Alright",
  "preparingYourNewCard": "Preparing your new card",
  "verifyingYourDetails": "Verifying your details",
  "bankRejectedYourRequest": "The bank rejected your request",
  "cardIsCancelled": "Card is cancelled",
  "cardIsActive": "Card is Active",
  "cardIsFrozen": "Card is Frozen",
  "thisCanTakeUpto3daysCourier":
      "This can take up to 3 working days after which our courier may contact you for the delivery",
  "thisCanTakeUpto3days": "This can take up to 3 working days.",
  "bankRejectedSubtitle":
      "Our support team will contact you to tackle the situation. If you need to get in touch, don't hesitate to use the button below.",
  "parent_replace_card_waiting_screen.deliveredSubtitle":
      "You've received the new card. Next step 👉🏽 card activation!",
  "usuallyTakesPendingSubtitle":
      "Usually takes up to 2 working days. Then we'll handle the cards to Aramex. They will tackle the delivery address and time.",
  "usuallyTakesNotIssuedSubtitle":
      "Usually takes up to 2 working days. Then we'll send you the card.",
  "deliveredSubtitle": "We know, you have received it 👀 Waste no time!",
  "cancelledSubtitle": "Your card is Cancelled",
  "activeSubtitle": "Your card is Active",
  "frozenSubtitle": "Your card is Frozen",
  "cardPrintingInProgress": "Card printing in progress",
  "verifyingDetails": "Verifying details",
  "bankRejectedRequest": "The bank rejected request",
  "activateTheCard": "Activate the card!",
  "request": "Request",
  "moneyRequested": "Money requested",
  "cancelRequest": "Cancel request",
  "goals_history": "Goals history",
  "createGoal": "Create goal",
  "oneYear": "1 year",
  "sixMonths": "6 months",
  "threeMonths": "3 months",
  "oneMonth": "1 month",
  "activate": "Activate",
  "cardWillArrive": "Card will arrive within 7 days",
  "aramexWill": "Aramex will contact you to get the delivery address and time",
  "costsSAR": "Costs SAR @replaceCardFee",
  "thisAmountWill": "This amount will be deducted from your balance to confirm the replacement",
  "replaceCardTeen": "Replace card",
  "replaceTheCard": "Replace the card?",
  "youCannotUndo":
      "You cannot undo this action. SAR @replaceCardFee will be deducted from your ANB balance to pay for the replacement.",
  "confirmPay": "Confirm & Pay SAR @replaceCardFee",
  "cardNumberAPIDisable": "Card number API disabled",
  "allowanceSet": "Allowance set",
  "allowancePaused": "Allowance paused",
  "allowanceUnavailable": "Allowance unavailable",
  "cancelAllowance": "Cancel allowance",
  "cancelAllowance?": "Cancel allowance?",
  "yes": "Yes",
  "no": "No",
  "frequency": "Frequency",
  "setAllowance": "Set allowance",
  "nameAllowance": "@firstName's allowance",
  "doNotShareItWith": "Do not share it with anyone!",
  "pinChanged": "PIN changed",
  "enterNewPin": "Enter new PIN again",
  "toMakeSure": "To make sure everything is correct",
  "thePinCodes": "The PIN codes didn't match. Please try again.",
  "enterNewCardPin": "Enter new card PIN",
  "thePinMayBeReq": "Please do not share PIN with anyone",
  "howMuchAndWhenDo": "How much and when do\nyou want to pay?",
  "weekly": "Weekly",
  "monthly": "Monthly",
  "biweekly": "Biweekly",
  "decline": "Decline",
  "slideToSend": "Slide to send",
  "moneySent": "Money sent",
  "weWillStillSendYou": "You’ll still receive critical notifications by default.",
  "turnOnNotification": "Turn on notifications for Cashee",
  "weSendOnlyEssential": "We send only essential updates of your account and activity.",
  "familyTitle": "Family title",
  "nickName": "Nickname",
  "nicknameUpdated": "Nickname updated",
  "updateNickname": "Update nickname",
  "updateProfilePic": "Update profile picture",
  "removeProfilePic": "Profile picture removed successfully",
  "requestDeclined": "Request declined",
  "declineNameRequest": "Decline @firstName's request?",
  "save": "Save",
  "picUpdate": "Picture updated",
  "sentItToNumber": "We sent it to @number",
  "sentItToRegisteredMobileNumber": "We sent it to your registered mobile number",
  "passcodeDidntMatch": "The passcodes didn't match. Try again.",
  "toChangeYourEmail": "To change your email or phone number, ",
  "he": "he",
  "she": "she",
  "him": "him",
  "her": "her",
  "his": "his",
  "test_select_user_screen.parent_app": "Parent App",
  "test_select_user_screen.child_app": "Child App",
  "create_goal_controller.keep_your_skirt":
      "Keep your shirt on 😎 The max goal amount we can handle is @currency 1000.",
  "create_goal_controller.goal_created": "Goal created",
  "parent_children_wallet_section.savings_balance": "Savings balance, @currency",
  "parent_children_spend_tab.spending_balance": "Spending balance, @currency",
  "parent_children_spend_tab.send_money": "Send money",
  "parent_children_spend_tab.set_up_allowance": "Set up allowance",
  "parent_children_spend_tab.regular_income_will":
      "Regular income can help @firstName plan to save better and spend wisely",
  "goal_history_section.withdraw": "Withdraw",
  "goal_history_section.end_goal": "End goal",
  "parent_children_screen.myANBBalance": "My ANB balance, @balance",
  "send_money_screen.toChild": "To @firstName",
  "send_money_screen.anbBalance": "My ANB balance: @balance",
  "send_money_screen.addMessage": "Add message?",
  "send_money_screen.send": "Send",
  "send_money_screen.topUpYourAccount":
      "Top up your account to send money to @firstName (Your account balance: @balance)",
  "send_money_success_screen.moneySentTo": "Money sent to @firstName",
  "send_money_controller.lowBalance": "You have only @balance in your ANB account",
  "send_money_controller.zeroBalance":
      "Your anb account balance: @balance. Please top up your account to send money.",
  "app_screen.powered_by": "powered by",
  "create_anb_account_screen.createANBAccount": "Create ANB account",
  "create_anb_account_screen.toUseCashee":
      "To use Cashee you need an ANB account. Since you don't have one, let's quickly open it. This will take up to 3 minuates.",
  "create_anb_account_screen.haveAnIssue": "Have an issue?",
  "parent_verify_details_screen.verifyDetails": "We're verifying your details",
  "parent_verify_details_screen.processMayTakeTime":
      "This process may take from a few seconds to a few minutes. Turn on notifications for the app, and we'll let you know when you can continue.",
"parent_verify_details_controller.changeNationalId": "Change national ID",
  "parent_account_ready_screen.accountReady": "Your account is ready!",
  "parent_account_ready_screen.addYourChild":
      "Now let’s create an account for your child. Go to account settings in the app to add more.",
"parent_child_nid_screen.enterChildNid": "Enter your child’s national ID",
  "parent_child_verify_details_screen.verifyDetails": "Verifying child details",
  "parent_child_verify_details_screen.processWillTakeTime":
      "This process may take from a few seconds to a few minutes. Turn on notifications for the app, and we’ll let you know when you can continue.",
  "parent_child_email_verification_screen.enterEmail": "Enter @name's email",
  "parent_child_email_verification_screen.description":
      "@heshe’ll use it to sign in to the app, as well as receive essential emails from Cashee and ANB",
  "parent_child_confirm_email_screen.confirmEmail": "Confirm the email",
  "parent_child_phone_screen.enterPhone": "Enter your child ’s mobile number",
  "parent_child_phone_screen.alreadyCreated":
      "If your child has already created their profile, we will connect it with yours when you enter the same number they used",
  "parent_child_all_set_screen.allSet": "All set!",
  "parent_child_all_set_screen.sendMoney":
      "@name’s card needs to be activated before you can send @himher money. Until then, enjoy exploring the app!",
  "incorrect_address_atom.incorrectAddress": "Incorrect address",
  "incorrect_address_atom.weUseTheAddress":
      "We use the address you provided for your ANB account. You can change it in your ANB app or from account settings on ",
  "incorrect_address_atom.theANBWebsite": "the ANB website.",
  "incorrect_address_atom.afterYouUpdate":
      "After you update the address, it will automatically be updated here. This process may take some time, so turn on your notifications and we'll keep you updated. We save your progress, so you can close the Cashee app while you’re waiting.",
  "incorrect_address_atom.ifTheUpdateIsNot":
      "If the update is not reflected in the Cashee app, hit the ‘Refresh’ button:",
  "incorrect_address_atom.ifYouStillFacing":
      "If you're still facing an issue after the address was updated for your ANB account, ",
  "incorrect_address_atom.contactOurSupport": "contact our support.",
  "parent_review_details_screen.reviewDetails": "Review details",
  "parent_review_details_screen.weAreGoingToUse":
      "These will be used for your Cashee account. To correct anything ",
  "parent_review_details_screen.cardsWillBeDelivered":
      "Cashee cards will be delivered to this address, so please make sure it's the right one. ",
  "parent_review_details_screen.incorrectAddress": "Incorrect address?",
  "parent_child_review_details_screen.enterNameAndReview":
      "Enter your child’s name and review details",
  "parent_child_review_details_screen.weAreGoingToUse":
      "We'll use these for their Cashee account. To change anything, ",
  "sign_in_password_screen.enterPassword": "Enter password",
  "sign_in_password_screen.for": "for @mobile",
  "email_verification_molecule.noAccount": "I don’t have an account",
  "choose_card_molecule.bolt_description_part1": "Energy, drive, and action. ",
  "choose_card_molecule.bolt_description_part2": "Team Bolt",
  "choose_card_molecule.bolt_description_part3":
      " is all about adventures, trying new stuff, and having fun.",
  "choose_card_molecule.rocket_description_part1":
      "Exploring new horizons and achieving big goals. With ",
  "choose_card_molecule.rocket_description_part2": "Team Rocket",
  "choose_card_molecule.rocket_description_part3": " the sky is the limit.",
  "choose_card_molecule.heart_description_part1":
  "Passion, intuition, and a certain kind of stubborness. With ",
  "choose_card_molecule.heart_description_part2": "Team Heart",
  "choose_card_molecule.heart_description_part3": "success is in balancing the head and the heart.",
  "parent_child_choose_card_screen.title": "Choose a card",
  "parent_child_choose_card_screen.subTitle": "Ask @name what team @heShe wants to join",
  "parent_set_profile_screen.setProfilePicture": "Set profile picture",
  "parent_set_profile_screen.buildBetterConnection": "This will be visible to your child",
  "set_profile_picture_organism.takePhoto": "Take a photo",
  "delete_picture_atom.deletePicture": "Delete picture",
  "setup_teen_set_profile_picture.setProfilePicture": "Set profile picture",
  "setup_teen_set_profile_picture.thisIsHow":
      "This is how your parent and other Cashee users will see you in the app",
  "setup_teen_set_profile_picture.thisWillBeVisible":
      "This will be visible to your parent and other users. Select your own image or pick one of our avatars!",
  "setup_teen_all_set_screen.readyToGo": "You’re ready to go!",
  "setup_teen_all_set_screen.exploreTheApp":
      "You can request and spend money only after you activate the card. Despite this, enjoy exploring the app.",
  "setup_teen_all_set_screen.createFlowSubtitle":
      "You can request for and spend money only after activating your Cashee card. Until then, enjoy exploring the app.",
  "unlock_passcode_screen.title": "Enter your passcode",
  "create_invite_parent_screen.ourWebsite": "Our Website",
  "create_invite_parent_screen.appStore": "App Store",
  "create_invite_parent_screen.googlePlay": "Google Play",
  "create_invite_parent_screen.press": "Press",
  "create_invite_parent_screen.lucidity": "Lucidity insights article",
  "create_invite_parent_screen.social": "Social",
  "create_invite_parent_screen.insta": "Instagram",
  "create_invite_parent_screen.fb": "Facebook",
  "create_invite_parent_screen.tiktok": "TikTok",
  "create_invite_parent_screen.twit": "Twitter",
  "create_invite_parent_screen.linkedin": "LinkedIn",
  "parent_nickname_screen.howDoesYour": "How does your child address you?",
  "parent_nickname_screen.makeAppFriendly":
      "We need this to make the app even more friendly. For example, if it’s ‘mom,’ we’ll tell a child they received money from mom, etc.",
  "setup_teen_nickname_screen.whatIsYourNickname": "What’s your nickname?",
  "setup_teen_nickname_screen.useItForLeaderboards":
      "We’ll use it instead of your real name for the Leaderboards, and other neat social features we’re working on. @parent sees your real name, though 😏",
  "setup_teen_nickname_screen.useItForReferalProgram":
      "We'll use it for our Referral Program, leaderboards, and other cool social features we're working on.",
  "phone_number_screen.enterPhone": "Enter your phone number",
  "choice_screen.greatWork": "Great work so far! Please tell us who you are 😁",
  "choice_screen.parent": "I’m a parent",
  "choice_screen.teen": "I'm 6-14 years old",
  "parent_agreement_screen.createProfile": "Let's create your parent profile",
  "parent_agreement_screen.ackImpStuff":
      "Select the boxes below to acknowledge the important stuff",
  "parent_agreement_screen.father": "I'm a father or a legal guardian",
  "parent_profile_complete_screen.profileComplete": "Your Cashee profile is complete!",
  "parent_profile_complete_screen.nextStep":
      "Next step — let's create your account. We will save your progress so you can easily continue where you left off.",
  "parent_child_account_connected_screen.connected":
      "Your child’s account has been connected to yours",
  "parent_nid_screen.enterYourNationalId": "Enter your national ID",
  "parent_nid_screen.requiredNid":
      "We require your national ID for your KYC process, as required by the Saudi Central Bank",
  "parent_child_nid_screen.enterYourNationalId": "Enter your child’s national ID",
  "setup_teen_agreement_screen.welcome": "Welcome to team @team!",
  "setup_teen_agreement_screen.setupAccount": "Let’s quickly set up your Cashee account",
  "dob_molecule.notAParent":
      "Cashee is for 6–14 year olds and their parents. Your age unfortunately doesn't fall within acceptable limits. Please contact support to clarify further.",
  "dob_molecule.notATeen": "Cashee is for children from 6–14 y.o.",
  "dob_molecule.dobMolecule": "DOBMolecule parseStrict function broke",
  "parent_dob_screen.enterDob": "Enter your date of birth",
  "parent_child_dob_screen.enterDob": "Enter your child’s date of birth",
  "email_verification_molecule.receiveEmails": "Receive essential emails about your activity",
  "parent_confirm_email_controller.useAnotherEmail": "Use another email",
  "create_anb_account_screen.createAnbAccount":
      "Already created your ANB account but still see this message? Hit the ‘Refresh’ button:",
  "parent_child_otp_controller.useAnotherPhone": "Use another phone number",
  "parent_activity_screen.allActivities": "All activities",
  "parent_activity_screen.myTransactions": "My transactions",
  "parent_activity_screen.events": "Events",
  "activity_list_molecule.noActivitiesAvailable": "No activities available",
  "activity_list_molecule.endOfList": "You saw everything! This is the end of the list.",
  "faq_screen.whatDoYouNeed": "What do you need help with?",
  "faq_screen.didNotFindTheAns": "Didn't find the answers?",
  "password_molecule.thePasswordMust": "The password must contain:",
  "password_molecule.number": "Number",
  "password_molecule.tenCharacters": "10+ characters",
  "password_molecule.upperLetter": "Uppercase letter",
  "password_molecule.lowerLetter": "Lowercase letter",
  "passcode_molecule.thePasscodeDidNotMatch": "The passcode didn't match, Try again.",
  "apple_wallet_molecule.digits": "•••• 1820",
  "apple_wallet_molecule.cardAddedToApple": "Card added to Apple Wallet",
  "apple_wallet_molecule.addYourCard": "Add your card to Apple Wallet",
  "apple_wallet_molecule.payInStores":
      "Pay in stores and online with your phone anywhere Apple Pay is accepted",
  "apple_wallet_molecule.addToAppleWallet": "Add to Apple Wallet",
  "apple_wallet_molecule.removeFromApple": "Remove from Apple Wallet",
  "apple_wallet_molecule.removeTheCardFrom": "Remove the card from Apple Wallet?",
  "apple_wallet_molecule.youWontBeAble": "You won't be able to pay with your card using the phone",
  "apple_wallet_molecule.remove": "Remove",
  "apple_wallet_molecule.openAppleWallet": "Open Apple Wallet",
  "text_field_atom.fieldIsMandatory": "Field is mandatory",
  "teen_card_atom.theCardIsFrozen": "Card frozen",
  "teen_card_atom.spendingBalance": "Spending balance",
  "teen_card_atom.savingBalance": "Saving balance",
  "teen_card_atom.sendMoney": "Send money",
  "sign_out_atom.signOut": "Sign out",
  "sign_out_atom.youWillHaveToEnter":
      "You'll have to enter your phone number and password to sign in again",
  "request_money_parent_atom.hasRequested": "@name has requested",
  "parent_request_money.hasRequested": "@firstName has requested",
  "request_button_atom.requested": "requested...",
  "end_goal_atom.endWithdraw": "End & Withdraw",
  "create_goal_atom.createGoal": "Create goal",
  "create_goal_atom.goalSubtitleParent":
      "Learning to save money is an important life skill. Create a goal for @firstName to encourage @himher to start saving for something.",
  "create_goal_atom.goalSubtitleTeen":
      "Learning to put money aside is as essential as making them. Start with something small and improve your skills as you grow up.",
  "cashee_card_atom.yourCardCancelled": "Your card is cancelled",
  "cashee_maintenance_screen.casheeMaintenanceScreen": "Cashee Maintenance Screen",
  "unlock_forgot_passcode_screen.resetPasscode": "Reset passcode?",
  "unlock_forgot_passcode_screen.willSendCodeTo":
      "We’ll send a code to your registered phone number. Enter the code here to create a new passcode.",
  "unlock_forgot_passcode_screen.sendResetCode": "Send reset code",
  "create_teen_welcome_screen.welcomeTeamHeart": "Welcome to Team Heart!",
  "create_teen_welcome_screen.onlyYourNickname":
      "You only need to set up your nickname and profile picture now!",
  "create_teen_invite_parent_screen.nowItsTimeToInvite": "Now it's time to invite your parent",
  "create_teen_invite_parent_screen.yourProfileHasBeen":
      "Your profile has been created. We now need your father or legal guardian to complete the process of creating your account.",
  "create_teen_invite_parent_screen.lovingCashee":
      "Loving Cashee? Share it with your friends and help them raise money-smart teens.",
  "create_teen_invite_parent_screen.turnOnNotificationForApp":
      "Turn on notifications for us let you know when your account is created and then you can add the finishing touches.",
  "create_teen_invite_parent_screen.turnOnNotification": "Turn on notifications",
  "create_teen_invite_parent_screen.parentWantToLearn": "Parents want to learn about cashee?",
  "create_teen_invite_parent_screen.hereAreFewUseful": "Here are a few useful links you can share",
  "create_teen_invite_parent_screen.linkCopied": "@title link copied",
  "create_teen_choose_card_screen.chooseYourCard": "Choose your card",
  "create_teen_choose_card_screen.chooseWisely": "Choose wisely — you cannot change it later",
  "create_teen_choose_card_screen.letCreateYourCashee": "Let's create your Cashee profile",
  "update_parent_nickname_screen.updateFamilyTitle": "Update family title",
  "update_parent_profile_picture_screen.letYourChildBuild": "This will be visible to your child",
  "parent_otpverify_screen.weSentItTo": "We sent it to @phone",
  "spend_wallet_section.cardNumberAPIDisable": "Card number API disabled",
  "teen_setpin_alright_screen.doNotShareItWith": "Do not share it with anyone!",
  "teen_setpin_alright_screen.pinChanged": "PIN changed",
  "teen_setpin_confirm_screen.enterNewPin": "Enter new PIN again",
  "teen_setpin_confirm_screen.toMakeSure": "To make sure everything is correct",
  "teen_setpin_confirm_screen.thePinCodes": "The PIN codes didn't match. Please try again.",
  "teen_setpin_create_screen.enterNewCardPin": "Enter new card PIN",
  "teen_setpin_create_screen.thePinMayBeReq": "Please do not share PIN with anyone",
  "teen_replace_card_alright_screen.newCardOrdered": "New card ordered",
  "teen_replace_card_alright_screen.aramexWillContact":
      "Aramex will contact you to arrange the delivery",
  "teen_replace_card_screen.cardReplace": "Card replacement",
  "teen_replace_card_screen.ifYouLostTheCurrent": "In case the card is lost or stolen",
  "teen_replace_card_screen.yourCardWillBloc": "Your card will be blocked!",
  "teen_replace_card_screen.youeAccountWill":
      "Your account will temporarily go into a view mode. You won't able to receive and spend money until you activate your new card.",
  "teen_replace_card_screen.cardWillArrive": "New card will arrive within 7 days",
  "teen_replace_card_screen.aramexWill":
      "Our courier company may contact you for the delivery address and time",
  "teen_replace_card_screen.costsSAR": "Cost: SAR 80",
  "teen_replace_card_screen.thisAmountWill": "This amount will be deducted from your account",
  "teen_replace_card_screen.replaceCard": "Replace card",
  "teen_replace_card_screen.replaceTheCard": "Replace the card?",
  "teen_replace_card_screen.youCannotUndo":
      "Sorry, You cannot undo this action. SAR 60 will be deducted from your ANB balance to pay for the replacement.",
  "teen_replace_card_screen.confirmPay": "Confirm & Pay SAR 60",
  "teen_replace_card_screen.orderANewCard": "Order a new card request",
  "teen_replace_card_screen.iWouldLike":
      "Hello,\n\n I would like to put in a request to re-issue a new Cashee card. I understand my account will be charged SAR 60.00 + 20% VAT as card re-issuance fees. I confirm that I have sufficient funds for this transaction to go through. \n\n Thank you!",
  "request_money_screen.whatFor": "What for?",
  "request_money_success_screen.requestAmount": "Request amount should be more then 0",
  "goal_top_up_screen.spendingBal": "Spending balance: @currency",
  "goal_top_up_screen.yourANBBalance": "Your ANB balance: @currency",
  "goal_history_screen.yourEnded": "Your Ended goals will appear here",
  "goal_history_screen.allTimeSaved": "All time saved: @currency",
  "create_goal_amount_screen.howMuchDo": "How much do you want to save?",
  "create_goal_amount_screen.createWithout": "Create without goal amount",
  "create_goal_deadline_screen.isThereDeadline": "Is there a deadline?",
  "create_goal_deadline_screen.createWithout": "Create without deadline",
  "create_goal_deadline_screen.tapToSet": "Tap to set",
  "create_goal_deadline_screen.specificDeadline": "Specific deadline",
  "create_goal_name_screen.whatAreYouSaving": "What are you saving for?",
  "edit_goal_amount_screen.howMuchDo": "How much do you want to save now?",
  "edit_goal_amount_screen.saveWithoutAmount": "Save without goal amount",
  "edit_goal_amount_screen.sheetTitle": "Removing the goal amount also removes the deadline",
  "edit_goal_amount_screen.sheetSubTitle":
      "If you just want to save as much as you can, continue saving and end the goal on the date you want",
  "edit_goal_amount_screen.sheetCtaBtn": "Remove deadline",
  "edit_goal_deadline_screen.whenDeadline": "When is the deadline?",
  "edit_goal_deadline_screen.newDeadline": "New deadline?",
  "edit_goal_deadline_screen.saveWithoutDeadline": "Sure? You near to save without deadline",
  "goal_details_screen.unfreeze": "Unfreeze the card to edit goal",
  "goal_details_screen.activate": "Activate your new card to edit goal",
  "goal_history_section.unfreeze": "Unfreeze card to unlock your savings",
  "goal_history_section.activate": "Please, activate card to unlock savings",
  "goal_topup_success_screen.addedTo": "Added to '@goalName'",
  "goal_topup_screen.goalForName": "@goalName for @firstName",
  "goal_withdraw_success_screen.teenTitle": "Withdrew to Spending balance",
  "goal_withdraw_success_screen.parentTitle": "Amount added to @firstName's spending balance",
  "goal_withdraw_screen.available": "Available Balance: @balance",
  "goals_section.unfreeze": "Unfreeze the card to create new goal",
  "goals_section.activate": "Activate your new card to create new goal",
  "request_location_screen.no_permission_ui.title":
      "Allow access to your precise location while using the app",
  "request_location_screen.no_permission_ui.subtitle":
      "Location sharing is necessary to use Cashee as per Saudi government regulations. This helps us keep your account safe. Please make sure you select \"Allow while using app\".",
  "request_location_screen.no_permission_ui.button": "Enable location sharing",
  "request_location_screen.limited_permission_ui.title":
      "Please, select 'Allow While Using App' with 'Precise Location'",
  "request_location_screen.limited_permission_ui.subtitle":
      "Location sharing is necessary to use Cashee as per Saudi government regulations around security and compliance. Please help us provide you with a more secure experience.",
  "request_location_screen.limited_permission_ui.button": "Location sharing settings",
  "location_service.enable_location_sharing.notifier1": "Please, enable location services",
  "location_service.enable_location_sharing.notifier2": "Please, select allow while using the app",
  "location_service.enable_location_sharing.notifier3": "Please, allow location permission",
  "location_service.enable_location_sharing.notifier4":
      "Open your cashee app settings and allow location permission to continue",
  "parent_replace_card_screen.ifLostTheCurrent":
      "If @firstName lost the current one or @heshe were scammed",
  "parent_replace_card_screen.cardWillbeBlock": "@firstName's card will be blocked!",
  "parent_replace_card_screen.thisDoesNot":
      "This doesn't affect your account. @firstName's account will temporarily go into a ‘view-only’ mode. @firstName won't able to make any transfers, and you will not be able to send @himher money.",
  "parent_replace_card_screen.cardWillArrive": "The New card will arrive within 7 days. Stay tuned!",
  "parent_replace_card_screen.courierCompany":
      "Our courier company may contact you for the delivery address and preferred time",
  "parent_replace_card_screen.costsSAR": "Costs SAR @replaceCardFee",
  "parent_replace_card_screen.amountWillBe": "This amount will be deducted from your account",
  "parent_replace_card_screen.notEnoughFund": "Insufficient funds",
  "parent_replace_card_screen.youNeedAtLeast":
      "Please top up your ANB account so we can charge you SAR @replaceCardFee for card replacement. In the meantime, you can freeze @firstName's card as a precaution.",
  "children_card_view_controller.thereIsSomeProblem":
      "There's a problem in changing card status. please try again later.",
  "teenHomeController.thereIsSomeProblem": 
      "There's a problem in changing card status. please try again later.",
  "dummy_card_activation_screen.cardActivateSuccess": "Card activated successfully!",
  "dummy_card_activation_screen.activateYourCasheeCard": "Activate your Cashee Card",
  "dummy_card_activation_screen.activateCashee": "Activate @firstName's Cashee Card",
  "dummy_card_activation_screen.enterTheLast4Digit":
      "Enter the last 4 digits of your Cashee Card to activate it.",
  "dummy_card_activation_screen.enterTheLastDigit":
      "Enter the last 4 digits of @firstName's Cashee Card to activate it.",
  "parent_children_details_screen.unfreeze":
      "Unfreeze @firstName's card to send @himher money and for @himher to use the card",
  "parent_children_details_screen.yourCardIs": "Your card is not issued yet",
  "parent_children_details_screen.yourCard":
      "Sorry, your card is cancelled! please contact support for issuing new card",
  "parent_children_details_screen.activate":
      "Please, activate @firstName's card in order to send @himher money",
  "parent_children_spend_tab.unfreeze": "Unfreeze the card to send allowances",
  "parent_children_spend_tab.unfreezeTheCard": "Unfreeze the card to set up allowance",
  "allowance_preview_screen.editAllowance": "Edit allowance",
  "allowance_preview_screen.amountWhen": "Amount & when to pay",
  "allowance_date_screen.forMonthsWith":
      "Money will be sent on the final day for months that have fewer days.",
  "allowance_frequency_screen.howOftenDoYou": "How often do you want\nto send @firstName money?",
  "allowance_frequency_screen.TheEasiest": "Best for beginners to learn budgeting",
  "allowance_frequency_screen.aSubstantial": "For those who are ready to plan ahead",
  "allowance_frequency_screen.letPlanLike": "For those who can stick to a budget",
  "parent_topup_screen.anbBalanceEquals": "ANB balance = Cashee balance",
  "parent_topup_screen.inCasheeYou":
      "If you need more funds, top up your ANB account for it to show instantly in the app. To top up, use the ANB banking platform with your name and IBAN number.",
  "request_money_pending_controller.cancelMoney": "Cancel money request?",
  "request_money_pending_controller.theRequestWillBe":
      "The request will be cancelled for both you and your parent",
  "request_money_pending_controller.teenCancelled": "Teen cancelled request money",
  "parent_nid_expiry_screen.enterExpiry": "Enter your national Id expiry date",
  "nid_expiry_molecule.nidExpired": "Your national Id is expired",
  "request_money_pending_controller.requestCancelled": "Request cancelled",
  "walkthroughTitle1": "Banking for the youth",
  "walkthroughSubTitle1": "The brand new way to learn, earn, save, and spend for kids and teens",
  "walkthroughTitle2": "Make sense of money",
  "walkthroughSubTitle2": "Track spends accurately to learn how to spend wisely",
  "walkthroughTitle3": "Hit those savings goals",
  "walkthroughSubTitle3": "Saving money made simple with goals and trackers",
  "walkthroughTitle4": "Hustle with confidence",
  "walkthroughSubTitle4": "Partnering with the best for a safe and secure experience",
  "walkthroughTitle5": "Learn to earn rewards",
  "walkthroughSubTitle5":
      "Bite-sized money lessons with rewards and Cashee coins to make learning fun!",
  "reset_password_screen.resetPassword": "Reset password?",
  "reset_password_screen.weWillSendCode":
      "We’ll send the OTP code to @phone. Please Enter the code here to create a new password.",
  "reset_password_screen.sendResetCode": "Send reset the OTP code",
  "reset_new_password_screen.saveNewPassword": "Save new password",
  "parentChildrenGoalSection.unfreezeCreateNewGoal":
      "Unfreeze @firstName's card to create new goal",
  "parentChildrenGoalSection.activateCreateNewGoal":
      "Activate @firstName's new card to create new goal",
  "spendWalletSection.activate":
      "You will be able to receive and\nspend money when you activate your\nnew card",
  "spendWalletSection.frozen":
      "You will be able to receive and\nspend money when you\nunfreeze your card",
  "editGoalController.nameCover": "Your name and cover updated successfully",
  "editGoalController.amountDeadline": "Goal amount and deadline set",
  "goalDetailsController.endGoal": "End goal?",
  "goalDetailsController.body": "@savedAmount from the goal will go to your spending balance.",
  "goalTopupController.insufficientErrorMsg":
      "You have only @spendBalance on your spending balance.",
  "goalWithdrawController.insufficientErrorMsg": "You have only @saveBalance to withdraw.",
  "teenProfileController.max20characters": "Max 20 characters",
  "choice_screen.tapErrorTeen": "Please ask your parent to register your account on Cashee",
  "goal_history.emptyList": "All transactions for the goal will appear here",
  "parent_child_review_details_screen.nameIsLong":"Name in English is too long (maximum is @length characters)"
};
